language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  
before_script:
  ## Install Composer
  - composer install
  - pecl install zip
  - echo "extension = zip.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: 
  - phpunit

matrix:
     allow_failures:
         - php: hhvm  
